#pragma once
#include "NativeGameplayTags.h"

namespace PDGameplayTags
{
	// Input
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Fire)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interact)

	// Damage
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage)

	// State - Debuff
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_LegDamaged)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_LegCrippled)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_ArmDamaged)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_ArmCrippled)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_Bleeding)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_Starving)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_Dehydrated)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_Fear)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_HeadInjury)

	// State - Buff
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_buff_Adrenaline)
	//State Aiming
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Aiming)
	//Weapon Type
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Rifle)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Shotgun)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Sniper)
	//AnimNotify
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Notify_EquipEnd)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Notify_ReloadEnd)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Notify_WeaponVisible)
}
