#pragma once
#include "NativeGameplayTags.h"

namespace PDGameplayTags
{
	// Input
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Fire)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interact)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Inventory)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Quest)
	
	//Input 핑
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ping);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_PingConfirm);

	// ── Input: 무기 - GAS 어빌리티로 처리 (AbilityInputActions)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Reload)

	// Input 무기
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Zoom)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_ToggleFireMode)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_SwitchSlot1)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_SwitchSlot2)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_SwitchSlot3)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_DropWeapon)

	// Damage
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage)

	// State - Debuff
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_LegDamaged)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_LegCrippled)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_ArmDamaged)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_ArmCrippled)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_Bleeding)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_Starving)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_Dehydrated)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_Fear)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Debuff_HeadInjury)

	// State - Buff
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_buff_Adrenaline)
	//State Aiming
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Aiming)
	//Weapon Type
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Rifle)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Shotgun)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Sniper)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Pistol)
	//AnimNotify
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Notify_EquipEnd)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Notify_ReloadEnd)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Notify_WeaponVisible)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_buff_Adrenaline)      

	// Weapon State
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_State_Firing)
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_State_Reloading)



}
